#!/usr/bin/env bash

BIN=~/.local/bin && \
VERSION="1.72.0" && \
curl -sSL \
"https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" \
-o "${BIN}/buf" && \

chmod +x "${BIN}/buf"