name: Publish NPM

on:
  push:
    branches:
      - master
    paths:
      - "gen/ts/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: gen/ts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Setup pnpm and node
        uses: pnpm/setup@v2
        with:
          version: 11
          runtime: node@24.15.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set package version
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
          else
            COUNT=$(git rev-list --count HEAD)
            SHA=$(git rev-parse --short HEAD)
            VERSION="0.0.0.${COUNT}.${SHA}"
          fi

          echo "Publishing version: $VERSION"
          pnpm version "$VERSION" --no-git-tag-version

      - name: Publish package
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}